name: Generate token and private checkout
description: Super small composite action to gen a github installation token and checkout a private repo
inputs:
  action:
    description: Centralised action to call
    required: true
  with:
    description: Centralised action with parameters
    default: ""

runs:
  using: composite
  steps:
    - run: |
        echo ${OH_ACTIONS_INSTALLATION_ID} | wc -c
        echo ${OH_ACTIONS_APP_ID} | wc -c
        echo ${OH_ACTIONS_PRIVATE_KEY} | wc -c
      shell: bash

    - name: Generate installation token
      id: gen-installation-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${OH_ACTIONS_APP_ID}
        private_key: ${OH_ACTIONS_PRIVATE_KEY}
        installation_id: ${OH_ACTIONS_INSTALLATION_ID}

    - name: Checkout centralised CI configs
      uses: actions/checkout@v2
      with:
        repository: Over-haul/gh-actions
        ref: v1
        token: ${{ steps.gen-installation-token.outputs.token }}
        path: .github/gh-actions
        persist-credentials: false

    - run: cd .github/gh-actions/${{ inputs.action }}
      shell: bash

    - uses: ./
      with: ${{ fromJson(inputs.with) }}
