name: Generate token and private checkout
description: Super small composite action to gen a github installation token and checkout a private repo
inputs:
  action:
    description: Centralised action to call
    required: true
  with:
    description: Centralised action with parameters
    default: ""
  private_key:
    description: key
    required: true

runs:
  using: composite
  steps:
    - run: |
        env_private_key=$(printf "%s" "${OH_ACTIONS_PRIVATE_KEY}" | base64 -w 0)
        sec_private_key=$(printf "%s" "${{ inputs.private_key }}" | base64 -w 0)
        echo "${env_private_key}"

        if [ "${env_private_key}" == "${sec_private_key}" ]; then
          echo "private key igual"
        fi
      shell: bash

    - run: |
        echo ${OH_ACTIONS_INSTALLATION_ID} | wc -c
        echo ${OH_ACTIONS_APP_ID} | wc -c
        echo ${OH_ACTIONS_PRIVATE_KEY} | wc -c
      shell: bash

    - name: Generate installation token
      id: gen-installation-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${OH_ACTIONS_APP_ID}
        private_key: ${OH_ACTIONS_PRIVATE_KEY}
        repository: Over-haul/gh-actions

    - name: Checkout centralised CI configs
      uses: actions/checkout@v2
      with:
        repository: Over-haul/gh-actions
        ref: v1
        token: ${{ steps.gen-installation-token.outputs.token }}
        path: .github/gh-actions
        persist-credentials: false

    - run: cd .github/gh-actions/${{ inputs.action }}
      shell: bash

    - uses: ./
      with: ${{ fromJson(inputs.with) }}
