name: Generate token and private checkout
description: Super small composite action to gen a github installation token and checkout a private repo
inputs:
  app_id:
    description: GitHub app id
    required: true
  private_key:
    description: GitHub app private key
    required: true
  installation_id:
    description: GitHub app installation id
    required: true
  repository:
    description: Repository to checkout
    required: true
  ref:
    description: Git ref to checkout
    required: true
  path:
    description: Path to checkout on
    default: .
outputs:
  token:
    description: GitHub token generated
    value: ${{ steps.gen-installation-token.outputs.token }}

runs:
  using: composite
  steps:
    - name: Generate installation token
      id: gen-installation-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.private_key }}
        installation_id: ${{ inputs.installation_id }}

    - name: Checkout centralised CI configs
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ steps.gen-installation-token.outputs.token }}
        path: ${{ inputs.path }}
        persist-credentials: false
